volumes:
  meus-links-pg-data: {}

services:
  meus-links-core:
    image: sameersbn/postgresql:14
    container_name: meus-links-core
    ports:
      - "6900:5432"
    environment:
      DB_NAME: meus-links-core
      DB_USER: admin
      DB_PASS: password
      PG_PASSWORD: password
    restart: no
    volumes:
      - meus-links-pg-data:/var/lib/postgresql
